import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/registry'
import MuiRegistry from '@/lib/MuiRegistry' // 👈 NEW
import GlobalStyles from '@/styles/GlobalStyles'
import ThemeProvider from '@/components/ThemeProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning={true}>
        <MuiRegistry>
          <StyledComponentsRegistry>
            <GlobalStyles />
            <ThemeProvider>{children}</ThemeProvider>
          </StyledComponentsRegistry>
        </MuiRegistry>
      </body>
    </html>
  )
}
